In [1]:
import pandas as pd
import numpy as np

#import random
#import itertools

from sklearn.preprocessing import StandardScaler, OneHotEncoder
#from sklearn.decomposition import PCA
from sklearn.model_selection import (train_test_split, 
                                     cross_val_score,
                                     RandomizedSearchCV, 
                                     GridSearchCV)


from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.utils import shuffle
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (accuracy_score,  
                             roc_curve,
                             roc_auc_score,
                             make_scorer,
                             auc)

from sklearn.model_selection import (train_test_split,  
                                     cross_val_score)
from catboost import Pool, CatBoostClassifier
import lightgbm as lgb
import warnings
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
RELEVANCE = '2020-02-01'
RND = 12345

sns.set(color_codes=True)
pd.set_option('display.max_columns', 40) # настройка отображения таблиц
pd.set_option('display.max_rows', 90) # настройка отображения таблиц

warnings.filterwarnings('ignore')

In [3]:
dataset = ['./datasets/final_provider/contract.csv', 
           './datasets/final_provider/internet.csv', 
           './datasets/final_provider/personal.csv',
           './datasets/final_provider/phone.csv']

# словарь с парами 'имя_таблицы:DataFrame' для удобства итерации по датафреймам. позже вынести в глобальные
telecom = {}

# Функция читате файл csv
def read_files(name_df, file): 
    try:
        name_df = pd.read_csv(file)
    except:
        print('Не удалось прочитать', file, 'проверьте расположение файла')
    return name_df
# Функция разбирает пути из списка, выделяет из каждого имя файла и записывает в индекс словаря: имя 
# а результат работы функции read_files в значение 
def read_files_get_list(files):
    for file in files:
        only_file_name = file.split("/")[-1][0:-4]
        telecom[only_file_name] = read_files(only_file_name, file)

read_files_get_list(dataset)

In [4]:
globals().update(telecom) # Передаем названия и объекты таблиц в глобальное пространство имен
df_telecom = contract.merge(internet, how='left', on= 'customerID')
df_telecom = df_telecom.merge(personal, how='left', on= 'customerID')
df_telecom = df_telecom.merge(phone, how='left', on= 'customerID')
# preview(df_telecom

In [5]:
df_telecom['isOut'] = np.where(df_telecom['EndDate'] == 'No', 0, 1)

In [6]:
df_telecom['EndDate'].replace('No', np.NaN, inplace = True)

In [7]:
# Функция получает список столбцов для замены типа на datetime64. 
# Ищет столбцы по названиям во фреймах списка "datasets" и заменяет найденные на datetime64
# с обработкой возможных ошибок
def replace_to_date(replace_list, data):
    for column in replace_list:
        if column in data.columns:
            if data[column].dtypes != 'datetime64[ns]':
                print('Попытка заменить тип данных {0}'.format(column))
                try:
                    data[column] = pd.to_datetime(data[column], format = '%Y-%m-%dT%H:%M:%S')
                    print('Успех!')
                except:
                    print('Отказ! Ошибка при изменении типа!')
            else:
                print('Отказ! {0} Тип уже был datetime64'.format(column))

In [8]:
# меняем тип данных в 'BeginDate', 'EndDate' на datetime 
date_list = ['BeginDate', 'EndDate']

replace_to_date(date_list, df_telecom)

Попытка заменить тип данных BeginDate
Успех!
Попытка заменить тип данных EndDate
Успех!

In [10]:
df_telecom

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,gender,SeniorCitizen,Partner,Dependents,MultipleLines,isOut
0,7590-VHVEG,2020-01-01,NaT,Month-to-month,Yes,Electronic check,29.85,29.85,DSL,No,Yes,No,No,No,No,Female,0,Yes,No,NaN,0
1,5575-GNVDE,2017-04-01,NaT,One year,No,Mailed check,56.95,1889.5,DSL,Yes,No,Yes,No,No,No,Male,0,No,No,No,0
2,3668-QPYBK,2019-10-01,2019-12-01,Month-to-month,Yes,Mailed check,53.85,108.15,DSL,Yes,Yes,No,No,No,No,Male,0,No,No,No,1
3,7795-CFOCW,2016-05-01,NaT,One year,No,Bank transfer (automatic),42.30,1840.75,DSL,Yes,No,Yes,Yes,No,No,Male,0,No,No,NaN,0
4,9237-HQITU,2019-09-01,2019-11-01,Month-to-month,Yes,Electronic check,70.70,151.65,Fiber optic,No,No,No,No,No,No,Female,0,No,No,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,2018-02-01,NaT,One year,Yes,Mailed check,84.80,1990.5,DSL,Yes,No,Yes,Yes,Yes,Yes,Male,0,Yes,Yes,Yes,0
7039,2234-XADUH,2014-02-01,NaT,One year,Yes,Credit card (automatic),103.20,7362.9,Fiber optic,No,Yes,Yes,No,Yes,Yes,Female,0,Yes,Yes,Yes,0
7040,4801-JZAZL,2019-03-01,NaT,Month-to-month,Yes,Electronic check,29.60,346.45,DSL,Yes,No,No,No,No,No,Female,0,Yes,Yes,NaN,0
7041,8361-LTMKD,2019-07-01,2019-11-01,Month-to-month,Yes,Mailed check,74.40,306.6,Fiber optic,No,No,No,No,No,No,Male,1,Yes,No,Yes,1
7042,3186-AJIEK,2014-08-01,NaT,Two year,Yes,Bank transfer (automatic),105.65,6844.5,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Male,0,No,No,No,0